version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn build website
      - save_cache:
          key: webmasterkit-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  deploy_staging:
    name: Deploy staging
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          key: webmasterkit-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo 'export SYNCANO_PROJECT_INSTANCE=$STAGING_SYNCANO_PROJECT_INSTANCE' >> $BASH_ENV
      - run: npx syncano-cli deploy
      - run: npx syncano-cli hosting config website -b true # --cname YOUR_CNAME
      - run: npx syncano-cli hosting sync website

  deploy_production:
    name: Deploy production
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          key: webmasterkit-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo 'export SYNCANO_PROJECT_INSTANCE=$PRODUCTION_SYNCANO_PROJECT_INSTANCE' >> $BASH_ENV
      - run: npx syncano-cli deploy
      - run: npx syncano-cli hosting config website -b true # --cname YOUR_CNAME
      - run: npx syncano-cli hosting sync website

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: production
